nests/config/routes.rb
Rails.application.routes.draw do

  root 'welcome#dashboard'

  resources :users do
    resources :posts
  end
  

  post "/signin/verify" => "sessions#create", as: :auth
  get "signin" => "sessions#new", as: :sign_in
  get "signout" => "sessions#destroy", as: :sign_out

end

nests/app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

nests/app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_secure_password
end

nests/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :find_current_user

  def find_current_user
    @current_user = User.find_by id: session[:user_id]
  end
end

nests/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    user_id = params[:user_id]
    user = User.find(user_id)
    @posts = user.posts
  end
end

nests/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:email]
    password = params[:password]

    # find by email
    user = User.find_by email: email
    # verify the password
    if user.try(:authenticate, password)
      # sign them in
      session[:user_id] = user.id
      redirect_to root_path
    else
      # or render the form
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

nests/app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def show
    @user = User.find params[:id]
  end

  def authenticate_user!
    if signed_in?
    else
      redirect_to sign_in_path
    end
  end

  def signed_in?
    session[:user_id].to_i > 0
  end

end

nests/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def dashboard
    @users = User.all
  end
end

nests/app/helpers/application_helper.rb
module ApplicationHelper
end

nests/app/helpers/posts_helper.rb
module PostsHelper
end

nests/app/helpers/sessions_helper.rb
module SessionsHelper
end

nests/app/helpers/users_helper.rb
module UsersHelper
end

nests/app/helpers/welcome_helper.rb
module WelcomeHelper
end

nests/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nests</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if @current_user %>
  YO! <%= @current_user.email %> | <%= link_to "Sign Out", sign_out_path %>
<% end %>

<%= yield %>

</body>
</html>

nests/app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <h1><%= post.title %></h1>
  <%= simple_format post.body %>
<% end %>

nests/app/views/users/show.html.erb
<h1><%= @user.email %></h1>
<p>
  Profile info goes here
</p>
<%= link_to "View Posts", user_posts_path(@user) %>

nests/app/views/welcome/dashboard.html.erb
<h1>Here are the blogs</h1>

<ul>
  <% @users.each do |user|%>
    <li><%= link_to user.email, user %></li>
  <% end %>
</ul>